### PR TITLE
Porting the library to Python 3.6

### PR DESCRIPTION
**Pull request by sateles**
I ran the _2to3_ tool that converts old python 2 constructs to python 3 constructs and changed the numpy.load function to read the NN file using the 'latin1' enconding. It's working just fine.

### CODE REVIEW

**Comment by erickrf** [comment]
This looks good, but if I understood correctly, the changed files are not compatible with Python 2, right?

**Comment by sateles** [comment]
Yes. There is no compatibility with Python 2. 
Well, I think that would be interesting to maintain both versions. That way we can use the library in new projects and keep it synchronized with popular packages that are often present in NLP research (gensim, nltk, sklern, numpy...). What do you think?

**Comment by erickrf** [comment]
I think that keeping the code compatible with both versions is the ideal, but I never really examined the details. I suppose some `__future__` and `six` imports should cover most of the cases in the Python side, no? I'm not sure about the cython extension.

**Comment by renatofcorrea** [comment]
Sateles, 
Your python 3 nlpnet version can run the POS tagger example? I also do the 2to3 conversion, but got a error running the POS tagger example. The error was:

  File "C:\Anaconda\lib\site-packages\nlpnet\metadata.py", line 111, in load_from_file
NameError: name 'cPickle' is not defined

**Comment by erickrf** [comment]
@renatofcorrea you can import cPickle from six

**Comment by sateles** [comment]
Yes, the POS tagger should work fine. I had used it.

**Comment by sateles** [comment]
I intend to come back and help actively to maintain this package. It has some nice features. I just need a couple of weeks to have some time available.

**Comment by erickrf** [comment]
I incorporated most of these changes in the last commit. I haven't tested training new models, but running the trained ones works fine in both python 2 and 3.

**Pull request closed without merging**
